#!/usr/bin/python3
#
# Purpose: Program to print email replies
# Program: emailReplies.py
# Author:  Wilson Crawford

# Calendar Module
from datetime import datetime

# Put the current date in the now variable.
now = datetime.now()

cmd = ""
while cmd != '20':
    print("")
    print("*************************************************************************")
    print("**************************    Email Replies    **************************")
    print("*************************************************************************")
    print(now.strftime("Day: " + "%A"))
    print(now.strftime("Date: " + "%B %d"))
    print(now.strftime("Time: " + "%H:%M%p"))
    print("")
    print("1. Quote Reply.")
    print("2. I have created an Incident from your email.")
    print("3. Completed Repairs on your laptop.")
    print("4. Need to look at the phone to troubleshoot the issue.")
    print("5. Let me know your availability.")
    print("6. Followup on incident before closing.")
    print("7. Loaner laptops at the help desk.")
    print("8. Please let me know when you are available for remote trouble shooting.")
    print("9. Please let me know if this has resolved the issue.")
    print("10. Attached is the inventory transform form.")
    print("11. Ok, it should have installed by now....")
    print("12. New laptop that is ready to deploy to your office. ")
    print("13. Request to install software with SCCM")



#    print("15. Reply 15 ")
#    print("16. Reply 16 ")
#    print("17. Reply 17 ")
#    print("18. Reply 18 ")
#    print("19. Reply 19 ")
    print("\n20. Quit")
    print("\n")

    cmd = input("\rCommand : ")
    if cmd == '1':
        print("")
        print("Good Morning / Good Afternoon,")
        print("")
        print("Please see the attached PDF for your requested quote.")
        print("If you would like to proceed with the order please forward ")
        print("the quote and chart string to Kayla.Mcchristian@untdallas.edu")
        print("")
        print("Please let me know if I can be of further assistance.")
        print("")
        print("Thank you,")
        print("\n")
    elif cmd == '2':
        print("Good Morning / Good Afternoon,")
        print("")
        print("I have received your email.  Also, I have created an incident ")
        print("in Service Now to address this issue. ")
        print("")
        print("The incident number is : ")
        print("")
        print("Please let me know if I can be of further assistance.")
        print("")
        print("Thank you,")
        print("\n")
    elif cmd == '3':
        print("Good Morning / Good Afternoon,")
        print("")
        print("I have completed the repairs on the laptop and it is ready to return to you.")
        print("If you would like it to be delivered to your office ")
        print("please respond with the building and office number.")
        print("")
        print("Please let me know if I can be of further assistance.")
        print("")
        print("Thank you,")
        print("\n")
    elif cmd == '4':
        print("Good Morning / Good Afternoon,")
        print("")
        print("On the incident of , I have received your incident request.")
        print("")
        print("I will need to look at the phone to troubleshoot the issue.")
        print("")
        print("Please respond with your building and office number.")
        print("")
        print("Let me know if I can be of further assistance.")
        print("")
        print("Thank you,")
        print("\n")
    elif cmd == '5':
        print("Good Morning / Good Afternoon,")
        print("")
        print("On the incident of "", I have received your request.")
        print("")
        print("Please let me know your availability, so that I can further trouble shoot the issue.")
        print("")
        print("I am available most times Monday through Friday 8:30 AM to 4:30 PM.")
        print("")
        print("Please let me know the best time for you.")
        print("")
        print("Thank you,")
        print("\n")
        print("Wilson")
    elif cmd == '6':
        print("Good Morning / Good Afternoon,")
        print("")
        print("I am following up on the incident of "".")
        print("")
        print("So far I have completed these steps to resolve the issue.")
        print("")
        print("Please let me know if you need anything else from me before I close the request.")
        print("")
        print("Thank you,")
        print("\n")
        print("Wilson")
    elif cmd == '7':
        print("Good Morning / Good Afternoon,")
        print("")
        print("I believe the help desk in Student Center has loaner laptops.")
        print("")
        print("UNT Dallas faculty and staff should be able to check them out from there.")
        print("")
        print("Let me know if I can be of further assistance.")
        print("")
        print("Thank you,")
        print("\n")
        print("Wilson")
    elif cmd == '8':
        print("Good Morning / Good Afternoon,")
        print("")
        print("Please let me know when you will be available to trouble shoot this issue.")
        print("")
        print("I can send you remote assist instructions.")
        print("")
        print("Thank you,")
        print("\n")
        print("Wilson")
    elif cmd == '9':
        print("Good Morning / Good Afternoon,")
        print("")
        print("Please let me know if this has resolved the issue.")
        print("")
    elif cmd == '10':
        print("Good Morning / Good Afternoon,")
        print("")
        print("Attached is the inventory transfer form for the TRIO laptops.")
        print("")
        print("Please sign and return so the Property manager can update the property records.")
        print("")
        print("Also please include the building and room number where the laptops will be used.")
        print("")
        print("Thank you,")
        print("\n")
        print("Wilson")
    elif cmd == '11':
        print("Ok, it should have installed by now.")
        print("")
        print("Please try this.")
        print("")
        print("Restart the computer and verify that is is connected to the wired network.")
        print("")
        print("If that does not work let me know and i can connect remotely to further trouble shoot.")
        print("")
        print("Thank you,")
        print("Wilson")
    elif cmd == '12':
        print("Good Morning / Good Afternoon,")
        print("")
        print("I have a new laptop that is ready to deploy to your office.  This laptop will replace the old laptop.")
        print("")
        print("If possible, please back up your files to One Drive so that I can pick up the old laptop.")
        print("")
        print("Please let me know when you will be available.  I am available most times Monday through Friday 8:30 AM to 4:30 PM.")
        print("")
        print("Thank you,")
        print("Wilson")
    elif cmd == '13':
        print("Good Morning / Good Afternoon,")
        print("")
        print("For this request, please ensure the computer is connected to the wired network.")
        print("")
        print("Then restart the computer.  The software installation should start shortly after the restart.")
        print("")
        print("Please allow some time for the software to install.  Typically 30 minutes to an hour.")
        print("")
        print("Please let me know if this has resolved the issue.")
        print("")
        print("Thank you,")
        print("Wilson")
    elif cmd != '20':
        print("Invalid command!")
                
    
